"""GrantScribe — funder-side LOI receipt verifier.

Anyone who receives an LOI generated by GrantScribe can verify that it was
anchored in a real grants.gov opportunity at draft time, without trusting the
sender:

    python verify_loi.py --letter received_loi.txt              # offline
    python verify_loi.py --letter received_loi.txt --live       # also re-fetch from grants.gov

Or pipe the letter via stdin:

    cat received_loi.txt | python verify_loi.py

Offline checks:
- The receipt block is present and well-formed.
- The receipt's `grant_canonical_sha256` matches a recomputed hash over the
  receipt's own identifier fields (opportunity_number / URL / close_date).
  This proves the receipt's identifiers haven't been internally tampered with.
- The `grant_url` points at grants.gov.

Live check (with `--live`):
- The opportunity number is re-fetched from grants.gov.
- The canonical hash of the *live* payload is recomputed and compared to the
  receipt's `grant_canonical_sha256`. If they match, the receipt is anchored
  in the live grants.gov API at the time of verification.

Exit code 0 iff every check passes.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

from loi_receipt import parse_receipt, verify_receipt_live, verify_receipt_offline


def _read_letter(path_or_dash: str | None) -> str:
    if path_or_dash and path_or_dash != "-":
        return Path(path_or_dash).read_text()
    return sys.stdin.read()


def _print_result(result: dict) -> None:
    overall = "PASS" if result["verified"] else "FAIL"
    print(f"\nReceipt verification: {overall}\n")
    for c in result["checks"]:
        mark = "✓" if c["passed"] else "✗"
        print(f"  {mark} {c['name']}")
        if c.get("detail"):
            print(f"      {c['detail']}")
    if result.get("note"):
        print(f"\nnote: {result['note']}")
    if result.get("live_grant"):
        g = result["live_grant"]
        print(f"\nLive grants.gov record at verification time:")
        print(f"  title:              {g.get('title')}")
        print(f"  agency:             {g.get('agency')}")
        print(f"  opportunity_number: {g.get('opportunity_number')}")
        print(f"  url:                {g.get('url')}")
        print(f"  close_date:         {g.get('close_date')}")


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(
        description="Verify a GrantScribe LOI receipt — funder-side audit tool."
    )
    p.add_argument("--letter", help="Path to a file containing the LOI (with receipt block). Use '-' or omit to read from stdin.")
    p.add_argument("--live", action="store_true",
                   help="Also re-fetch the grant from grants.gov and verify the canonical hash matches the live payload.")
    args = p.parse_args(argv)

    text = _read_letter(args.letter)
    receipt = parse_receipt(text)
    if receipt is None:
        print("FAIL: no GRANTSCRIBE VERIFICATION RECEIPT block found in input.", file=sys.stderr)
        print("      This LOI does not carry a verifiable receipt; treat with the same trust", file=sys.stderr)
        print("      as any unsigned LLM-generated prose.", file=sys.stderr)
        return 2

    print("Parsed receipt:")
    for k, v in receipt.items():
        if k.startswith("_"):
            continue
        print(f"  {k}: {v}")

    result = verify_receipt_live(receipt) if args.live else verify_receipt_offline(receipt)
    _print_result(result)
    return 0 if result["verified"] else 1


if __name__ == "__main__":
    sys.exit(main())
